version: '2.1'
services:

    postgres:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=airflow
            - POSTGRES_PASSWORD=airflow
            - POSTGRES_DB=airflow
        volumes:
            - ./airflow-db/postgresql/data:/var/lib/postgresql/data

    webserver:
        image: puckel/docker-airflow
        restart: always
        depends_on:
            - postgres
        environment:
            # User defined
            - MAX_DOWNLOADS=10

            # Backend
            - PROJECT_HOME=/app
            - LOAD_EX=n
            - EXECUTOR=Local
        volumes:
            - ./videos:/videos
            - ./dags:/usr/local/airflow/dags
            - ./airflow-logs:/usr/local/airflow/logs
        ports:
            - "8080:8080"
        command: webserver
        healthcheck:
            test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
            interval: 30s
            timeout: 30s
            retries: 3

